insert into public.programmes (code, title, summary, modules, target_dimensions, intended_capability, route_fit, sort_order) values
('AIF-101','AI Foundations & Practical Competency',
 'Build confident, correct everyday use of generative AI/LLMs — from mental model to reliable prompting and verification.',
 '["What LLMs can and cannot do","Prompting that works: structure, context, iteration","Verifying and correcting AI output","Safe, appropriate everyday use"]'::jsonb,
 '["D1","D5"]'::jsonb,
 'Individuals can use approved AI tools confidently and verify outputs before relying on them.',
 '["individual","team","organisation","client"]'::jsonb, 10),
('AIP-201','Applied Prompting & Workflow Patterns',
 'Move from ad-hoc prompts to reusable prompting methods, templates and assistants for recurring work.',
 '["Reusable prompt templates","Task-specific prompting patterns","Building Gems / copilots / assistants","Refining and iterating for consistency"]'::jsonb,
 '["D1","D3","D4"]'::jsonb,
 'Users create repeatable, consistent AI-assisted outputs for their recurring tasks.',
 '["individual","team","organisation","client"]'::jsonb, 20),
('AIW-301','AI Workflow Optimisation',
 'Identify and redesign recurring tasks and process handoffs around AI to cut manual effort and rework.',
 '["Spotting AI-assisted workflow opportunities","Redesigning a recurring task with AI","Standardising AI-assisted steps","Measuring time and quality impact"]'::jsonb,
 '["D4","D8"]'::jsonb,
 'Teams can identify, implement and standardise AI-assisted workflows.',
 '["team","organisation","client"]'::jsonb, 30),
('AIG-401','Responsible AI, Data & Governance',
 'Establish clear, practical rules for what data can be used with AI, how outputs are verified, and how risk is controlled.',
 '["Data, privacy and confidentiality with AI","Approved tools and safe-use practice","Verification and human judgement","Lightweight governance that people follow"]'::jsonb,
 '["D5"]'::jsonb,
 'Relevant people apply AI safely within data, privacy and governance requirements.',
 '["team","organisation","client"]'::jsonb, 40),
('AIL-501','Leading AI Adoption for Managers',
 'Equip managers and leaders to set direction, enable approved AI use and connect adoption to outcomes.',
 '["Setting direction and expectations","Enabling approved AI use in the team","Coaching adoption and champions","Connecting AI use to measurable outcomes"]'::jsonb,
 '["D6","D7","D8"]'::jsonb,
 'Managers and leaders can guide responsible AI adoption and build capability.',
 '["team","organisation","client"]'::jsonb, 50),
('AIA-601','AI Adoption & Capability Uplift Programme',
 'Broad, role-based capability building to raise consistent adoption across a team or organisation.',
 '["Role-based practical AI skills","Building internal AI champions","Consistent team practices","Reinforcement and workplace transfer"]'::jsonb,
 '["D3","D7"]'::jsonb,
 'Teams use AI more consistently across common work with growing internal capability.',
 '["team","organisation","client"]'::jsonb, 60),
('AIV-701','AI Investment Value Realisation',
 'Turn licensed AI/LLM investment into measured, workflow-level value — closing the gap between access and adoption.',
 '["Activating licensed tools for real work","From productivity to workflow value","Measuring adoption and outcomes","Scaling what works"]'::jsonb,
 '["D2","D8"]'::jsonb,
 'Organisations realise measurable value from their AI-tool investment.',
 '["organisation","team","client"]'::jsonb, 70)
on conflict (code) do nothing;
