-- Bilingual programme catalog: Bahasa Malaysia columns + seed values.
alter table public.programmes
  add column if not exists title_bm text,
  add column if not exists summary_bm text,
  add column if not exists intended_capability_bm text,
  add column if not exists modules_bm jsonb not null default '[]'::jsonb;

update public.programmes set title_bm='Asas AI & Kompetensi Praktikal', summary_bm='Bina penggunaan AI generatif/LLM harian yang yakin dan betul — daripada model minda kepada gesaan dan pengesahan yang boleh dipercayai.', intended_capability_bm='Individu boleh menggunakan alat AI yang diluluskan dengan yakin dan mengesahkan output sebelum bergantung padanya.', modules_bm='["Apa yang LLM boleh dan tidak boleh lakukan","Gesaan yang berkesan: struktur, konteks, lelaran","Mengesahkan dan membetulkan output AI","Penggunaan harian yang selamat dan sesuai"]'::jsonb where code='AIF-101';
update public.programmes set title_bm='Gesaan Gunaan & Corak Aliran Kerja', summary_bm='Beralih daripada gesaan ad-hoc kepada kaedah gesaan, templat dan pembantu yang boleh diguna semula untuk kerja berulang.', intended_capability_bm='Pengguna mencipta output berbantukan AI yang boleh diulang dan konsisten untuk tugas berulang mereka.', modules_bm='["Templat gesaan boleh guna semula","Corak gesaan khusus tugas","Membina Gems / copilot / pembantu","Memperhalus dan mengulang untuk konsistensi"]'::jsonb where code='AIP-201';
update public.programmes set title_bm='Pengoptimuman Aliran Kerja AI', summary_bm='Kenal pasti dan reka bentuk semula tugas berulang dan serahan proses di sekitar AI untuk mengurangkan usaha manual dan kerja semula.', intended_capability_bm='Pasukan boleh mengenal pasti, melaksana dan menyeragamkan aliran kerja berbantukan AI.', modules_bm='["Mengesan peluang aliran kerja berbantukan AI","Mereka bentuk semula tugas berulang dengan AI","Menyeragamkan langkah berbantukan AI","Mengukur kesan masa dan kualiti"]'::jsonb where code='AIW-301';
update public.programmes set title_bm='AI Bertanggungjawab, Data & Tadbir Urus', summary_bm='Tetapkan peraturan yang jelas dan praktikal tentang data yang boleh digunakan dengan AI, cara output disahkan, dan cara risiko dikawal.', intended_capability_bm='Orang berkaitan menggunakan AI dengan selamat dalam keperluan data, privasi dan tadbir urus.', modules_bm='["Data, privasi dan kerahsiaan dengan AI","Alat diluluskan dan amalan penggunaan selamat","Pengesahan dan pertimbangan manusia","Tadbir urus ringkas yang dipatuhi orang"]'::jsonb where code='AIG-401';
update public.programmes set title_bm='Memimpin Penggunaan AI untuk Pengurus', summary_bm='Lengkapkan pengurus dan pemimpin untuk menetapkan hala tuju, membolehkan penggunaan AI yang diluluskan dan mengaitkan penggunaan dengan hasil.', intended_capability_bm='Pengurus dan pemimpin boleh membimbing penggunaan AI yang bertanggungjawab dan membina keupayaan.', modules_bm='["Menetapkan hala tuju dan jangkaan","Membolehkan penggunaan AI diluluskan dalam pasukan","Membimbing penggunaan dan juara","Mengaitkan penggunaan AI dengan hasil boleh diukur"]'::jsonb where code='AIL-501';
update public.programmes set title_bm='Program Penggunaan & Peningkatan Keupayaan AI', summary_bm='Pembinaan keupayaan berdasarkan peranan yang luas untuk meningkatkan penggunaan yang konsisten merentas pasukan atau organisasi.', intended_capability_bm='Pasukan menggunakan AI dengan lebih konsisten merentas kerja biasa dengan keupayaan dalaman yang semakin berkembang.', modules_bm='["Kemahiran AI praktikal berdasarkan peranan","Membina juara AI dalaman","Amalan pasukan yang konsisten","Pengukuhan dan pemindahan di tempat kerja"]'::jsonb where code='AIA-601';
update public.programmes set title_bm='Realisasi Nilai Pelaburan AI', summary_bm='Tukar pelaburan AI/LLM berlesen kepada nilai peringkat aliran kerja yang diukur — merapatkan jurang antara akses dan penggunaan.', intended_capability_bm='Organisasi merealisasikan nilai yang boleh diukur daripada pelaburan alat AI mereka.', modules_bm='["Mengaktifkan alat berlesen untuk kerja sebenar","Daripada produktiviti kepada nilai aliran kerja","Mengukur penggunaan dan hasil","Menskala apa yang berkesan"]'::jsonb where code='AIV-701';
